import {
  AppState,
  Booking,
  DriverVerificationRequest,
  FavoritePlace,
  LouageRide,
  Payment,
  Ticket,
  UserAccount,
} from './types';
import {
  TRANSIT_LINES,
  TRANSIT_LIVE_VEHICLES,
  TRANSIT_NEARBY,
} from './data/transitCatalog';
import { TUNISIAN_CITIES as CITY_OPTIONS } from './data/locationOptions';

export const TUNISIAN_CITIES = CITY_OPTIONS;

export const DRIVER_DOCUMENT_LABELS = {
  driving_license: 'Permis de conduire',
  national_id: 'Carte d identite nationale',
  vehicle_insurance: 'Assurance vehicule',
  vehicle_registration: 'Carte grise',
} as const;

export const PAYMENT_METHODS = [
  {
    id: 'bank_card',
    label: 'Carte bancaire',
    subtitle: 'Validation immediate via le connecteur backend',
  },
  {
    id: 'konnect',
    label: 'Konnect',
    subtitle: 'Passerelle tunisienne branchable cote serveur',
  },
  {
    id: 'flooss',
    label: 'Flooss',
    subtitle: 'Wallet mobile et encaissement backend',
  },
  {
    id: 'sps',
    label: 'SPS',
    subtitle: 'Paiement marchand avec etats persistants',
  },
  {
    id: 'd17',
    label: 'D17',
    subtitle: 'Paiement QR et suivi d etat backend',
  },
] as const;

export const LINES = TRANSIT_LINES;

export const LIVE_VEHICLES = TRANSIT_LIVE_VEHICLES;

function departureIso(daysFromNow: number, hourUtc: number, minuteUtc: number) {
  const departure = new Date();
  departure.setUTCDate(departure.getUTCDate() + daysFromNow);
  departure.setUTCHours(hourUtc, minuteUtc, 0, 0);
  return departure.toISOString();
}

function pastDepartureIso(daysAgo: number, hourUtc: number, minuteUtc: number) {
  return departureIso(-daysAgo, hourUtc, minuteUtc);
}

function offsetIso(baseIso: string, minutes: number) {
  return new Date(new Date(baseIso).getTime() + minutes * 60 * 1000).toISOString();
}

function buildTicketPayload(params: {
  ticketId: string;
  bookingId: string;
  validUntil: string;
  origin: string;
  destination: string;
  mode: 'metro' | 'bus' | 'louage';
}) {
  return JSON.stringify(params);
}

const ride1Departure = departureIso(1, 14, 30);
const ride2Departure = departureIso(1, 18, 15);
const ride3Departure = departureIso(2, 9, 0);
const ride4Departure = departureIso(2, 11, 30);
const ride5Departure = departureIso(1, 16, 0);
const ride6Departure = departureIso(2, 7, 15);
const ride7Departure = departureIso(3, 8, 30);
const ride8Departure = departureIso(3, 13, 45);
const ride9Departure = pastDepartureIso(2, 9, 15);
const ride10Departure = pastDepartureIso(1, 7, 50);
const ride11Departure = departureIso(1, 20, 10);
const ride12Departure = departureIso(1, 15, 45);
const ride13Departure = departureIso(2, 6, 30);
const ride14Departure = departureIso(2, 12, 20);
const ride15Departure = departureIso(1, 10, 0);
const ride16Departure = departureIso(3, 5, 50);
const ride17Departure = departureIso(3, 9, 40);
const ride18Departure = departureIso(2, 8, 10);
const ride19Departure = departureIso(1, 17, 20);
const ride20Departure = departureIso(2, 14, 50);

const bookingMetroActiveCreatedAt = offsetIso(ride1Departure, -24 * 60);
const bookingBusExpiredCreatedAt = offsetIso(ride9Departure, -180);
const bookingLinePendingCreatedAt = offsetIso(ride6Departure, -90);
const bookingRide1CreatedAt = offsetIso(ride1Departure, -180);
const bookingRide2CreatedAt = offsetIso(ride2Departure, -210);
const bookingRide9CreatedAt = offsetIso(ride9Departure, -240);
const bookingRide10CreatedAt = offsetIso(ride10Departure, -240);
const bookingRide3CancelledCreatedAt = offsetIso(ride3Departure, -300);
const bookingRide11CancelledCreatedAt = offsetIso(ride11Departure, -70);

const ticketMetroActiveValidUntil = offsetIso(bookingMetroActiveCreatedAt, 90);
const ticketBusExpiredValidUntil = offsetIso(bookingBusExpiredCreatedAt, 90);
const ticketRide1ValidUntil = offsetIso(ride1Departure, 6 * 60);
const ticketRide2ValidUntil = offsetIso(ride2Departure, 6 * 60);
const ticketRide9ValidUntil = offsetIso(ride9Departure, 6 * 60);
const ticketRide10ValidUntil = offsetIso(ride10Departure, 6 * 60);
const ticketRide3ValidUntil = offsetIso(ride3Departure, 6 * 60);
const ticketRide11ValidUntil = offsetIso(ride11Departure, 6 * 60);

export const SEED_USERS: UserAccount[] = [
  {
    id: 'admin-1',
    role: 'admin',
    email: 'admin@volta.tn',
    fullName: 'Equipe Admin Volta',
    city: 'Tunis',
    locale: 'fr-TN',
    createdAt: '2026-04-01T08:00:00.000Z',
    phoneVerified: true,
    verificationStatus: 'approved',
    avatarColor: '#0040a1',
    rating: 4.9,
    completedTrips: 0,
    penaltyCount: 0,
  },
  {
    id: 'passenger-1',
    role: 'passenger',
    email: 'imen@volta.tn',
    phone: '+21622111222',
    fullName: 'Imen Gharbi',
    city: 'Tunis',
    locale: 'fr-TN',
    createdAt: '2026-04-07T09:00:00.000Z',
    phoneVerified: true,
    verificationStatus: 'not_started',
    avatarColor: '#006d36',
    rating: 0,
    completedTrips: 0,
    penaltyCount: 0,
  },
  {
    id: 'driver-1',
    role: 'driver',
    email: 'hamed@volta.tn',
    phone: '+21655123456',
    fullName: 'Hamed Trabelsi',
    city: 'Tunis',
    locale: 'fr-TN',
    createdAt: '2026-04-02T07:00:00.000Z',
    dateOfBirth: '1988-09-14',
    gender: 'homme',
    phoneVerified: true,
    verificationStatus: 'approved',
    driverLineId: 'bus-104',
    avatarColor: '#0891b2',
    rating: 4.8,
    completedTrips: 126,
    penaltyCount: 1,
  },
  {
    id: 'driver-2',
    role: 'driver',
    email: 'salma.driver@volta.tn',
    phone: '+21699123456',
    fullName: 'Salma Ben Ali',
    city: 'Sfax',
    locale: 'fr-TN',
    createdAt: '2026-04-09T12:00:00.000Z',
    dateOfBirth: '1992-03-21',
    gender: 'femme',
    phoneVerified: true,
    verificationStatus: 'pending',
    avatarColor: '#7c3aed',
    rating: 4.6,
    completedTrips: 18,
    penaltyCount: 0,
  },
  {
    id: 'driver-3',
    role: 'driver',
    email: 'mourad.driver@volta.tn',
    phone: '+21658111222',
    fullName: 'Mourad Jlassi',
    city: 'Nabeul',
    locale: 'fr-TN',
    createdAt: '2026-04-05T10:15:00.000Z',
    dateOfBirth: '1990-11-05',
    gender: 'homme',
    phoneVerified: true,
    verificationStatus: 'rejected',
    avatarColor: '#d97706',
    rating: 4.1,
    completedTrips: 9,
    penaltyCount: 2,
  },
];

export const SEED_RIDES: LouageRide[] = [
  {
    id: 'ride-1',
    driverUserId: 'driver-1',
    departureCity: 'Tunis',
    destinationCity: 'Sousse',
    departureAt: ride1Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 31,
    vehicleModel: 'Toyota Hiace',
    plateNumber: '226 TUN 194',
    vehiclePhotoName: 'hiace-sousse.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-2',
    driverUserId: 'driver-1',
    departureCity: 'Sousse',
    destinationCity: 'Sfax',
    departureAt: ride2Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 22,
    vehicleModel: 'Peugeot Boxer',
    plateNumber: '144 TUN 508',
    vehiclePhotoName: 'boxer-sfax.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-3',
    driverUserId: 'driver-1',
    departureCity: 'Tunis',
    destinationCity: 'Nabeul',
    departureAt: ride3Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 14,
    vehicleModel: 'Renault Trafic',
    plateNumber: '132 TUN 887',
    vehiclePhotoName: 'trafic-nabeul.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-4',
    driverUserId: 'driver-1',
    departureCity: 'Beja',
    destinationCity: 'Gafsa',
    departureAt: ride4Departure,
    availableSeats: 3,
    totalSeats: 3,
    priceTnd: 42,
    vehicleModel: 'Mercedes Sprinter',
    plateNumber: '305 TUN 441',
    vehiclePhotoName: 'sprinter-gafsa.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-5',
    driverUserId: 'driver-1',
    departureCity: 'Sfax',
    destinationCity: 'Gabes',
    departureAt: ride5Departure,
    availableSeats: 3,
    totalSeats: 3,
    priceTnd: 18,
    vehicleModel: 'Fiat Ducato',
    plateNumber: '177 TUN 908',
    vehiclePhotoName: 'ducato-gabes.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-6',
    driverUserId: 'driver-1',
    departureCity: 'Monastir',
    destinationCity: 'Sousse',
    departureAt: ride6Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 12,
    vehicleModel: 'Peugeot Traveller',
    plateNumber: '411 TUN 120',
    vehiclePhotoName: 'traveller-sousse.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-7',
    driverUserId: 'driver-1',
    departureCity: 'Nabeul',
    destinationCity: 'Tunis',
    departureAt: ride7Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 14,
    vehicleModel: 'Citroen Jumper',
    plateNumber: '510 TUN 077',
    vehiclePhotoName: 'jumper-tunis.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-8',
    driverUserId: 'driver-1',
    departureCity: 'Gabes',
    destinationCity: 'Sfax',
    departureAt: ride8Departure,
    availableSeats: 3,
    totalSeats: 3,
    priceTnd: 18,
    vehicleModel: 'Ford Transit',
    plateNumber: '278 TUN 650',
    vehiclePhotoName: 'transit-sfax.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-9',
    driverUserId: 'driver-1',
    departureCity: 'Tunis',
    destinationCity: 'Monastir',
    departureAt: ride9Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 27,
    vehicleModel: 'Hyundai H1',
    plateNumber: '120 TUN 204',
    vehiclePhotoName: 'h1-monastir.jpg',
    status: 'completed',
    liveProofEnabled: true,
  },
  {
    id: 'ride-10',
    driverUserId: 'driver-1',
    departureCity: 'Sousse',
    destinationCity: 'Tunis',
    departureAt: ride10Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 29,
    vehicleModel: 'Volkswagen Transporter',
    plateNumber: '619 TUN 302',
    vehiclePhotoName: 'transporter-tunis.jpg',
    status: 'completed',
    liveProofEnabled: true,
  },
  {
    id: 'ride-11',
    driverUserId: 'driver-1',
    departureCity: 'Tunis',
    destinationCity: 'Bizerte',
    departureAt: ride11Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 19,
    vehicleModel: 'Nissan Urvan',
    plateNumber: '421 TUN 011',
    vehiclePhotoName: 'urvan-bizerte.jpg',
    status: 'cancelled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-12',
    driverUserId: 'driver-1',
    departureCity: 'Bizerte',
    destinationCity: 'Tunis',
    departureAt: ride12Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 20,
    vehicleModel: 'Mercedes Vito',
    plateNumber: '551 TUN 216',
    vehiclePhotoName: 'vito-tunis.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-13',
    driverUserId: 'driver-1',
    departureCity: 'Tunis',
    destinationCity: 'Hammamet',
    departureAt: ride13Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 17,
    vehicleModel: 'Renault Master',
    plateNumber: '337 TUN 481',
    vehiclePhotoName: 'master-hammamet.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-14',
    driverUserId: 'driver-1',
    departureCity: 'Sfax',
    destinationCity: 'Kairouan',
    departureAt: ride14Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 24,
    vehicleModel: 'Peugeot Expert',
    plateNumber: '804 TUN 653',
    vehiclePhotoName: 'expert-kairouan.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-15',
    driverUserId: 'driver-1',
    departureCity: 'Gabes',
    destinationCity: 'Medenine',
    departureAt: ride15Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 13,
    vehicleModel: 'Toyota Commuter',
    plateNumber: '128 TUN 904',
    vehiclePhotoName: 'commuter-medenine.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-16',
    driverUserId: 'driver-1',
    departureCity: 'Medenine',
    destinationCity: 'Tataouine',
    departureAt: ride16Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 16,
    vehicleModel: 'Fiat Scudo',
    plateNumber: '703 TUN 115',
    vehiclePhotoName: 'scudo-tataouine.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-17',
    driverUserId: 'driver-1',
    departureCity: 'Tozeur',
    destinationCity: 'Gafsa',
    departureAt: ride17Departure,
    availableSeats: 3,
    totalSeats: 3,
    priceTnd: 15,
    vehicleModel: 'Nissan NV350',
    plateNumber: '612 TUN 873',
    vehiclePhotoName: 'nv350-gafsa.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-18',
    driverUserId: 'driver-1',
    departureCity: 'Beja',
    destinationCity: 'Jendouba',
    departureAt: ride18Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 12,
    vehicleModel: 'Citroen SpaceTourer',
    plateNumber: '459 TUN 201',
    vehiclePhotoName: 'spacetourer-jendouba.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-19',
    driverUserId: 'driver-1',
    departureCity: 'Hammamet',
    destinationCity: 'Tunis',
    departureAt: ride19Departure,
    availableSeats: 3,
    totalSeats: 4,
    priceTnd: 16,
    vehicleModel: 'Volkswagen Caravelle',
    plateNumber: '288 TUN 764',
    vehiclePhotoName: 'caravelle-tunis.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
  {
    id: 'ride-20',
    driverUserId: 'driver-1',
    departureCity: 'Mahdia',
    destinationCity: 'Sousse',
    departureAt: ride20Departure,
    availableSeats: 4,
    totalSeats: 4,
    priceTnd: 15,
    vehicleModel: 'Opel Vivaro',
    plateNumber: '374 TUN 592',
    vehiclePhotoName: 'vivaro-sousse.jpg',
    status: 'scheduled',
    liveProofEnabled: true,
  },
];

export const SEED_VERIFICATION_REQUESTS: DriverVerificationRequest[] = [
  {
    id: 'verification-driver-2',
    userId: 'driver-2',
    status: 'pending',
    submittedAt: '2026-04-17T10:00:00.000Z',
    cityOfResidence: 'Sfax',
    documents: [
      { type: 'driving_license', name: 'permis_salma.pdf', uploadedAt: '2026-04-17T10:05:00.000Z' },
      { type: 'national_id', name: 'cin_salma.jpg', uploadedAt: '2026-04-17T10:06:00.000Z' },
      { type: 'vehicle_insurance', name: 'assurance_salma.pdf', uploadedAt: '2026-04-17T10:07:00.000Z' },
      { type: 'vehicle_registration', name: 'carte_grise_salma.pdf', uploadedAt: '2026-04-17T10:08:00.000Z' },
    ],
    applicantName: 'Salma Ben Ali',
    applicantEmail: 'salma.driver@volta.tn',
    applicantPhone: '+21699123456',
  },
  {
    id: 'verification-driver-1',
    userId: 'driver-1',
    status: 'approved',
    submittedAt: '2026-04-09T09:00:00.000Z',
    reviewedAt: '2026-04-09T13:30:00.000Z',
    reviewedBy: 'admin-1',
    cityOfResidence: 'Tunis',
    documents: [
      { type: 'driving_license', name: 'permis_hamed.pdf', uploadedAt: '2026-04-09T09:05:00.000Z' },
      { type: 'national_id', name: 'cin_hamed.jpg', uploadedAt: '2026-04-09T09:06:00.000Z' },
      { type: 'vehicle_insurance', name: 'assurance_hamed.pdf', uploadedAt: '2026-04-09T09:07:00.000Z' },
      { type: 'vehicle_registration', name: 'carte_grise_hamed.pdf', uploadedAt: '2026-04-09T09:08:00.000Z' },
    ],
    applicantName: 'Hamed Trabelsi',
    applicantEmail: 'hamed@volta.tn',
    applicantPhone: '+21655123456',
  },
  {
    id: 'verification-driver-3',
    userId: 'driver-3',
    status: 'rejected',
    submittedAt: '2026-04-12T11:20:00.000Z',
    reviewedAt: '2026-04-12T16:15:00.000Z',
    reviewedBy: 'admin-1',
    rejectionReason: 'Assurance expir ee et pieces illisibles.',
    cityOfResidence: 'Nabeul',
    documents: [
      { type: 'driving_license', name: 'permis_mourad.pdf', uploadedAt: '2026-04-12T11:25:00.000Z' },
      { type: 'national_id', name: 'cin_mourad.jpg', uploadedAt: '2026-04-12T11:26:00.000Z' },
      { type: 'vehicle_insurance', name: 'assurance_mourad.pdf', uploadedAt: '2026-04-12T11:27:00.000Z' },
      { type: 'vehicle_registration', name: 'carte_grise_mourad.pdf', uploadedAt: '2026-04-12T11:28:00.000Z' },
    ],
    applicantName: 'Mourad Jlassi',
    applicantEmail: 'mourad.driver@volta.tn',
    applicantPhone: '+21658111222',
  },
];

export const SEED_FAVORITES: FavoritePlace[] = [
  {
    id: 'fav-1',
    userId: 'passenger-1',
    label: 'Maison',
    city: 'Bardo',
    hint: 'Rue Habib Maazoun',
  },
  {
    id: 'fav-2',
    userId: 'passenger-1',
    label: 'Travail',
    city: 'Lac II',
    hint: 'Pole technologique',
  },
  {
    id: 'fav-3',
    userId: 'passenger-1',
    label: 'Tunis Marine',
    city: 'Tunis Marine',
    hint: 'Correspondance TGM et metro',
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'booking-line-metro-active',
    type: 'line_ticket',
    mode: 'metro',
    passengerUserId: 'passenger-1',
    lineId: 'metro-m1',
    createdAt: bookingMetroActiveCreatedAt,
    departureAt: offsetIso(bookingMetroActiveCreatedAt, 5),
    origin: 'Tunis Marine',
    destination: 'Ben Arous',
    seatsBooked: 1,
    amountTnd: 0.8,
    status: 'confirmed',
    paymentId: 'pay-line-metro-active',
    ticketId: 'ticket-line-metro-active',
    payoutStatus: 'n/a',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Ticket metro actif pour test backend.',
  },
  {
    id: 'booking-line-bus-expired',
    type: 'line_ticket',
    mode: 'bus',
    passengerUserId: 'passenger-1',
    lineId: 'bus-104',
    createdAt: bookingBusExpiredCreatedAt,
    departureAt: offsetIso(bookingBusExpiredCreatedAt, 5),
    origin: 'Tunis Marine',
    destination: 'Mannouba',
    seatsBooked: 1,
    amountTnd: 1.2,
    status: 'confirmed',
    paymentId: 'pay-line-bus-expired',
    ticketId: 'ticket-line-bus-expired',
    payoutStatus: 'n/a',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Ticket bus deja archive.',
  },
  {
    id: 'booking-line-pending',
    type: 'line_ticket',
    mode: 'bus',
    passengerUserId: 'passenger-1',
    lineId: 'bus-17b',
    createdAt: bookingLinePendingCreatedAt,
    departureAt: offsetIso(bookingLinePendingCreatedAt, 8),
    origin: 'Rades',
    destination: 'Tunis',
    seatsBooked: 1,
    amountTnd: 1.2,
    status: 'pending_payment',
    paymentId: 'pay-line-pending',
    payoutStatus: 'n/a',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Paiement encore en attente cote fournisseur.',
  },
  {
    id: 'booking-ride-1-confirmed',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-1',
    createdAt: bookingRide1CreatedAt,
    departureAt: ride1Departure,
    origin: 'Tunis',
    destination: 'Sousse',
    seatsBooked: 1,
    amountTnd: 31,
    status: 'confirmed',
    paymentId: 'pay-ride-1',
    ticketId: 'ticket-ride-1',
    payoutStatus: 'held',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Reservation louage confirmee avec payout retenu.',
  },
  {
    id: 'booking-ride-2-awaiting',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-2',
    createdAt: bookingRide2CreatedAt,
    departureAt: ride2Departure,
    origin: 'Sousse',
    destination: 'Sfax',
    seatsBooked: 1,
    amountTnd: 22,
    status: 'awaiting_passenger_confirmation',
    paymentId: 'pay-ride-2',
    ticketId: 'ticket-ride-2',
    payoutStatus: 'held',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Le conducteur attend la confirmation d arrivee.',
  },
  {
    id: 'booking-ride-9-completed',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-9',
    createdAt: bookingRide9CreatedAt,
    departureAt: ride9Departure,
    origin: 'Tunis',
    destination: 'Monastir',
    seatsBooked: 1,
    amountTnd: 27,
    status: 'completed',
    paymentId: 'pay-ride-9',
    ticketId: 'ticket-ride-9',
    payoutStatus: 'released',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Trajet termine et payout libere.',
  },
  {
    id: 'booking-ride-10-no-show',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-10',
    createdAt: bookingRide10CreatedAt,
    departureAt: ride10Departure,
    origin: 'Sousse',
    destination: 'Tunis',
    seatsBooked: 1,
    amountTnd: 29,
    status: 'no_show_reported',
    paymentId: 'pay-ride-10',
    ticketId: 'ticket-ride-10',
    payoutStatus: 'eligible_with_proof',
    refundStatus: 'none',
    penaltyPercent: 0,
    note: 'Absence voyageur validee avec preuve live recente.',
  },
  {
    id: 'booking-ride-3-cancelled-passenger',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-3',
    createdAt: bookingRide3CancelledCreatedAt,
    departureAt: ride3Departure,
    origin: 'Tunis',
    destination: 'Nabeul',
    seatsBooked: 1,
    amountTnd: 14,
    status: 'cancelled_by_passenger',
    paymentId: 'pay-ride-3-cancelled-passenger',
    ticketId: 'ticket-ride-3-cancelled-passenger',
    payoutStatus: 'refunded',
    refundStatus: 'refunded',
    penaltyPercent: 0,
    note: 'Annulation passager dans le delai de grace.',
  },
  {
    id: 'booking-ride-11-cancelled-driver',
    type: 'louage',
    mode: 'louage',
    passengerUserId: 'passenger-1',
    driverUserId: 'driver-1',
    rideId: 'ride-11',
    createdAt: bookingRide11CancelledCreatedAt,
    departureAt: ride11Departure,
    origin: 'Tunis',
    destination: 'Bizerte',
    seatsBooked: 1,
    amountTnd: 19,
    status: 'cancelled_by_driver',
    paymentId: 'pay-ride-11-cancelled-driver',
    ticketId: 'ticket-ride-11-cancelled-driver',
    payoutStatus: 'refunded',
    refundStatus: 'refunded',
    penaltyPercent: 10,
    note: 'Annulation conducteur tardive avec penalite 10%.',
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'ticket-line-metro-active',
    userId: 'passenger-1',
    bookingId: 'booking-line-metro-active',
    mode: 'metro',
    title: 'Metro Leger M1',
    validFrom: bookingMetroActiveCreatedAt,
    validUntil: ticketMetroActiveValidUntil,
    priceTnd: 0.8,
    zones: 'Tunis Marine - Ben Arous',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-line-metro-active',
      bookingId: 'booking-line-metro-active',
      validUntil: ticketMetroActiveValidUntil,
      origin: 'Tunis Marine',
      destination: 'Ben Arous',
      mode: 'metro',
    }),
    status: 'active',
  },
  {
    id: 'ticket-line-bus-expired',
    userId: 'passenger-1',
    bookingId: 'booking-line-bus-expired',
    mode: 'bus',
    title: 'Bus 104 Tunis Marine - Mannouba',
    validFrom: bookingBusExpiredCreatedAt,
    validUntil: ticketBusExpiredValidUntil,
    priceTnd: 1.2,
    zones: 'Tunis Marine - Mannouba',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-line-bus-expired',
      bookingId: 'booking-line-bus-expired',
      validUntil: ticketBusExpiredValidUntil,
      origin: 'Tunis Marine',
      destination: 'Mannouba',
      mode: 'bus',
    }),
    status: 'expired',
  },
  {
    id: 'ticket-ride-1',
    userId: 'passenger-1',
    bookingId: 'booking-ride-1-confirmed',
    mode: 'louage',
    title: 'Louage Tunis -> Sousse',
    validFrom: bookingRide1CreatedAt,
    validUntil: ticketRide1ValidUntil,
    priceTnd: 31,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-1',
      bookingId: 'booking-ride-1-confirmed',
      validUntil: ticketRide1ValidUntil,
      origin: 'Tunis',
      destination: 'Sousse',
      mode: 'louage',
    }),
    status: 'active',
  },
  {
    id: 'ticket-ride-2',
    userId: 'passenger-1',
    bookingId: 'booking-ride-2-awaiting',
    mode: 'louage',
    title: 'Louage Sousse -> Sfax',
    validFrom: bookingRide2CreatedAt,
    validUntil: ticketRide2ValidUntil,
    priceTnd: 22,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-2',
      bookingId: 'booking-ride-2-awaiting',
      validUntil: ticketRide2ValidUntil,
      origin: 'Sousse',
      destination: 'Sfax',
      mode: 'louage',
    }),
    status: 'active',
  },
  {
    id: 'ticket-ride-9',
    userId: 'passenger-1',
    bookingId: 'booking-ride-9-completed',
    mode: 'louage',
    title: 'Louage Tunis -> Monastir',
    validFrom: bookingRide9CreatedAt,
    validUntil: ticketRide9ValidUntil,
    priceTnd: 27,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-9',
      bookingId: 'booking-ride-9-completed',
      validUntil: ticketRide9ValidUntil,
      origin: 'Tunis',
      destination: 'Monastir',
      mode: 'louage',
    }),
    status: 'used',
  },
  {
    id: 'ticket-ride-10',
    userId: 'passenger-1',
    bookingId: 'booking-ride-10-no-show',
    mode: 'louage',
    title: 'Louage Sousse -> Tunis',
    validFrom: bookingRide10CreatedAt,
    validUntil: ticketRide10ValidUntil,
    priceTnd: 29,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-10',
      bookingId: 'booking-ride-10-no-show',
      validUntil: ticketRide10ValidUntil,
      origin: 'Sousse',
      destination: 'Tunis',
      mode: 'louage',
    }),
    status: 'cancelled',
  },
  {
    id: 'ticket-ride-3-cancelled-passenger',
    userId: 'passenger-1',
    bookingId: 'booking-ride-3-cancelled-passenger',
    mode: 'louage',
    title: 'Louage Tunis -> Nabeul',
    validFrom: bookingRide3CancelledCreatedAt,
    validUntil: ticketRide3ValidUntil,
    priceTnd: 14,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-3-cancelled-passenger',
      bookingId: 'booking-ride-3-cancelled-passenger',
      validUntil: ticketRide3ValidUntil,
      origin: 'Tunis',
      destination: 'Nabeul',
      mode: 'louage',
    }),
    status: 'cancelled',
  },
  {
    id: 'ticket-ride-11-cancelled-driver',
    userId: 'passenger-1',
    bookingId: 'booking-ride-11-cancelled-driver',
    mode: 'louage',
    title: 'Louage Tunis -> Bizerte',
    validFrom: bookingRide11CancelledCreatedAt,
    validUntil: ticketRide11ValidUntil,
    priceTnd: 19,
    zones: 'Interurbain',
    qrPayload: buildTicketPayload({
      ticketId: 'ticket-ride-11-cancelled-driver',
      bookingId: 'booking-ride-11-cancelled-driver',
      validUntil: ticketRide11ValidUntil,
      origin: 'Tunis',
      destination: 'Bizerte',
      mode: 'louage',
    }),
    status: 'cancelled',
  },
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: 'pay-line-metro-active',
    userId: 'passenger-1',
    bookingId: 'booking-line-metro-active',
    provider: 'bank_card',
    amountTnd: 0.8,
    createdAt: bookingMetroActiveCreatedAt,
    status: 'paid',
    payoutStatus: 'n/a',
    summary: 'Ticket metro M1 confirme.',
  },
  {
    id: 'pay-line-bus-expired',
    userId: 'passenger-1',
    bookingId: 'booking-line-bus-expired',
    provider: 'd17',
    amountTnd: 1.2,
    createdAt: bookingBusExpiredCreatedAt,
    status: 'paid',
    payoutStatus: 'n/a',
    summary: 'Ticket bus 104 archive.',
  },
  {
    id: 'pay-line-pending',
    userId: 'passenger-1',
    bookingId: 'booking-line-pending',
    provider: 'konnect',
    amountTnd: 1.2,
    createdAt: bookingLinePendingCreatedAt,
    status: 'pending',
    payoutStatus: 'n/a',
    summary: 'Paiement bus en attente de confirmation Konnect.',
  },
  {
    id: 'pay-ride-1',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-1-confirmed',
    provider: 'bank_card',
    amountTnd: 31,
    createdAt: bookingRide1CreatedAt,
    status: 'paid',
    payoutStatus: 'held',
    summary: 'Paiement louage Tunis -> Sousse retenu.',
  },
  {
    id: 'pay-ride-2',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-2-awaiting',
    provider: 'flooss',
    amountTnd: 22,
    createdAt: bookingRide2CreatedAt,
    status: 'paid',
    payoutStatus: 'held',
    summary: 'Paiement louage Sousse -> Sfax en attente de confirmation passager.',
  },
  {
    id: 'pay-ride-9',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-9-completed',
    provider: 'sps',
    amountTnd: 27,
    createdAt: bookingRide9CreatedAt,
    status: 'paid',
    payoutStatus: 'released',
    summary: 'Paiement libere apres trajet complete.',
  },
  {
    id: 'pay-ride-10',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-10-no-show',
    provider: 'bank_card',
    amountTnd: 29,
    createdAt: bookingRide10CreatedAt,
    status: 'paid',
    payoutStatus: 'eligible_with_proof',
    summary: 'No-show confirme avec preuve live recente.',
  },
  {
    id: 'pay-ride-3-cancelled-passenger',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-3-cancelled-passenger',
    provider: 'd17',
    amountTnd: 14,
    createdAt: bookingRide3CancelledCreatedAt,
    status: 'refunded',
    payoutStatus: 'refunded',
    summary: 'Remboursement passager apres annulation dans le delai.',
  },
  {
    id: 'pay-ride-11-cancelled-driver',
    userId: 'passenger-1',
    driverUserId: 'driver-1',
    bookingId: 'booking-ride-11-cancelled-driver',
    provider: 'konnect',
    amountTnd: 19,
    createdAt: bookingRide11CancelledCreatedAt,
    status: 'refunded',
    payoutStatus: 'refunded',
    summary: 'Remboursement integral apres annulation conducteur.',
  },
];

export const NEARBY_TRANSPORT = TRANSIT_NEARBY;

export function createEmptyState(): AppState {
  return {
    users: [],
    sessionUserId: null,
    verificationRequests: [],
    lines: [],
    liveVehicles: [],
    louageRides: [],
    bookings: [],
    tickets: [],
    payments: [],
    favorites: [],
    nearbyTransport: [],
    selectedLineId: 'metro-m1',
    locationEnabled: true,
    locale: 'fr-TN',
  };
}

export function createInitialState(): AppState {
  return {
    users: SEED_USERS,
    sessionUserId: null,
    verificationRequests: SEED_VERIFICATION_REQUESTS,
    lines: LINES,
    liveVehicles: LIVE_VEHICLES,
    louageRides: SEED_RIDES,
    bookings: SEED_BOOKINGS,
    tickets: SEED_TICKETS,
    payments: SEED_PAYMENTS,
    favorites: SEED_FAVORITES,
    nearbyTransport: NEARBY_TRANSPORT,
    selectedLineId: 'metro-m1',
    locationEnabled: true,
    locale: 'fr-TN',
  };
}
